export const SETTINGS_KEYS = {
  THEME_PRESET: 'papercache-theme-preset',
  FONT_FAMILY: 'papercache-font',
  SHOW_RULINGS: 'papercache-rulings',
  BG_TYPE: 'papercache-bg-type',
  BG_COLOR: 'papercache-bg-color',
  BG_IMAGE: 'papercache-bg-image',
  TEXT_COLOR: 'papercache-color-text',
  NUM_COLOR: 'papercache-color-num',
  SYM_COLOR: 'papercache-color-sym',
  AI_COLOR: 'papercache-color-ai',
  MATH_COLOR: 'papercache-color-math',
  API_BASE_URL: 'papercache-api-base-url',
  API_MODEL: 'papercache-api-model',
  AI_SYSTEM_PROMPT: 'papercache-ai-system-prompt',
  SHORTCUT_NEWNOTE: 'papercache-shortcut-newnote',
  SHORTCUT_TOGGLE: 'papercache-shortcut-toggle',
  LAUNCH_STARTUP: 'papercache-launch-startup',
} as const
